## Default server configuration
---
server:
  applicationConnectors:
    - type: http
      port: 8080


database:
  # the name of your JDBC driver
  driverClass: org.h2.Driver
  user: sa
  password: sa
  url: jdbc:h2:mem:test:DB_CLOSE_DELAY=-1
